### ISSUE TITLE
webinterface

### ISSUE THREAD

**Issue by bendixsonnenberg** [christoph-fricke/shpioneers.de#73]
I would really like it if this was done soon, so that linus can do all the stuff by himself

**Comment by christoph-fricke** [comment]
I want to do biology first before I join the next big project...

**Comment by bendixsonnenberg** [comment]
i did not think of such a narrow timeline
this has got quite a bit of time

**Comment by bendixsonnenberg** [comment]
we will have to take a look at robot.txt files so that crawlers form google dont mess with the webinterface

**Comment by christoph-fricke** [comment]
I also red the you can handle the crawlers in a meta tag so I am not sure which is the right way... Maybe we should do both... ;D

**Comment by christoph-fricke** [comment]
As far as I can the it we have an admin page now where you get to after you entered your password etc. And the admin page has links to sub pages for each topic where you can do your stuff...

I thought that it maybe would be a better UX if the current content of the admin page is the navbar and depending on which page you choose it gets displayed in the body... So we would basically have one admin page which provide the user a better experience when navigating around. 

I created a little concept art for the new admin page:

![concept](https://cloud.githubusercontent.com/assets/23103835/24701519/0d74eed2-19fb-11e7-834a-c3fd38ab17f0.PNG)

**Comment by bendixsonnenberg** [comment]
i like the idea but i think it would be a little bit to much effort for this project
i tought more along the lines of giving the current pages some css and then tell linus and jorina to learn to deal with it
unless you want to spend some time on this one.

**Comment by christoph-fricke** [comment]
Well a simple solution might be to include them as iframes but I am not sure how that would work out...

**Comment by bendixsonnenberg** [comment]
nice idea and that would also minimize the work we would have to do

**Comment by christoph-fricke** [comment]
We just have to see how much it works out responsive...

**Comment by bendixsonnenberg** [comment]
we could scale the iframe and that would scale the page inside

**Comment by bendixsonnenberg** [comment]
do you think we should use the backend names for labels?

**Comment by christoph-fricke** [comment]
That is what I was thinking to do... I mean we already have the names in place and ready to use through the json file, so why not use them...

They are meaningful enough in my opinion, expect "quotee" could get some work (maybe "quoter"?)...

**Comment by bendixsonnenberg** [comment]
https://www.merriam-webster.com/dictionary/quotee

**Comment by christoph-fricke** [comment]
Still sounds strange and they are saying that it is referring to the person who gets quoted not to the person who quotes someone...

**Comment by bendixsonnenberg** [comment]
it is the person who gets quoted

**Comment by bendixsonnenberg** [comment]
i just got an email from our webhosting service.
they are willing and able to give us a ssl certificat.

**Comment by christoph-fricke** [comment]
That's cool... Did they give you a date?

**Comment by bendixsonnenberg** [comment]
right now.
it is self signed so i would not recommend using it for the main page
we should just use it for the webinterface

**Comment by bendixsonnenberg** [comment]
is there anything left that we should do before we pull the webinterface?

**Comment by christoph-fricke** [comment]
I am not sure... I mean we have:
- A log in page
- Feedback on wrong log in (sucess redirects directly to board, so no feedback needed here)
- Admin board
- Navbar for editing achievments, sponsores, news and team
- Options to edit, remove, change order or add a new one
- inputs to do the edits
- save function
- inputs getting removed when topic is changed or element is got saved

I think I have listed everything what we have and I do not think the we need more stuff? So I guess the Webinterface is finished... Maybe we could just rename the folder to something like admin (is optional)...

The only think we can think about is a little button on the main page, leading to the webinterface, however I do not think that is needed as long as we have a folder name that everybody who have to can remember...

And I am not sure if they are able to create their own user, even with your nicely written instructions. I mean they were also not able to edit the content json files... 😞

I am not sure if it is a security problem or not, but everybody who reads the instructions on github or plays around a little bit is able to see the users.json (also on live server). Since we are using the default hash (aren't we?) they might be able to recreate the password out of the hash... Might be that I am wrong and it is not possible, but that would be a big problem...

**Comment by bendixsonnenberg** [comment]
it would be possible but only through bruteforcing their way into the system because the reason we use hashes is that the are only one way conversions of strings.
as far as i know there are also no rainbow tables for the php hashing algorithm

even so, it would be better if we could deny access to the .json files all together.
maybe through the .htaccess?

i would say that we can expect Linus and Jorina to remember a simple path.
 renaming is a goog idea

**Comment by christoph-fricke** [comment]
Is it possible to simply rename the folder? I think so or do you have any path into the folder? I will just use the refactor feature of my editor.... Safety first... xD

**Comment by christoph-fricke** [comment]
The idea with blocking the json files is a good idea...

**Comment by christoph-fricke** [comment]
@quannten24  is there anything left or can we merge it? There is still a project about making the php constants editable? Is that still a thing?

**Comment by bendixsonnenberg** [comment]
not really

i think we can merge
