### ISSUE TITLE
Feedback about existing email on sign up

### ISSUE THREAD

**Issue by christoph-fricke** [christoph-fricke/shpioneers.de#94]
@quannten24 We already talk about this and you said the we can't do it because the user could find out who already have subscribed to our newsletter.

But we actually give the user the information already. The user gets feedback if the email already exists after he confirms his subscription. It would just be a much better and more natural UX.

And many companies are doing it the same way so I do not think that there would be some law issues.

**Comment by bendixsonnenberg** [comment]
We dont tell the user wether the email adress actually exists.

  we just tell them wether their activation link did anything or not.

if you subscribe twice with the same email address and confirm one, then 
the second link wont work, but at that moment we wont know wether it is 
because the hash in the address line was deleted or if it never existed.


I also think we should discuss this over ts.
